### ISSUE TITLE
FileCmp returning false for even same content in Run.py

### ISSUE THREAD

**Issue by himanshu-dixit** [himanshu-dixit/Bezel-Online-Judge#5]
The input and ouput file sample is same, but the filecmp is returning false. Check
https://github.com/himanshu-dixit/Bezel-Online-Judge/commit/03935dffaaa74c85ff1857557c0e687dc8a7d31d

**Comment by utkarsh-dixit** [comment]
@himanshu-dixit Looks like, we didn't noticed new line in 35.in . I think this is the issue, so i am closing it for now. If the issue still persists after this, please reopen this issue.
